name = input("Enter your name: ")
year = int(input("Enter Discovery Year: "))
creature = input("Enter Creature Name: ")
planet = input("Enter Discovered Planet: ")
primary = input(" Enter Creature's Diet: ")
print(f"\n{'='*50}")
print(f"\n  XENO-BIOLOGY FIELD REPORT ")
print(f"\n{'='*50}")
print(f"Scientist: Dr. {name}")
print(f"Discovery Year: {year}")
print(f"\n{'-'*50}")
print(f"Creature Name: {creature}")
print(f"Home Planet: {planet}")
print(f"Primary Diet: {primary}")
print("  ")
print(f"Scientific Designation:{planet}-{creature}-{year}")
print(f"\n{'='*50}")