name = input( "What is your name? " )
gpa = float(input("Enter your GPA score (0.0-4.0): "))
hours = int(input("Enter your total credit hours: "))
print(f"\n{'='*40}")
print(f"Student's name {name}")
print(gpa >= 3.5 and hours >= 12)
if gpa < 3.5: print(f"{3.5-gpa: 2f} more GPA points needed.")
else: print(" ")
if hours < 12: print(f"{12-hours} more credits needed.")
else: print(" ")
print(f"\n{'='*40}")